Feature: Support blank lines in PAX headers

  As a developer using Apache Commons Compress
  I want TarArchiveInputStream to gracefully handle blank lines in PAX headers
  So that I can process tar archives generated by tools that produce such headers (e.g., certain versions of npm pack)

  Scenario: Read a TAR archive with blank lines in the PAX header
    Given a TAR archive input stream
    And the archive contains a PAX header entry
    And the PAX header data contains a blank line (a single newline character) between records
    When I call getNextTarEntry
    Then the blank line should be ignored
    And the next TAR entry should be successfully retrieved
    And no NegativeArraySizeException should be thrown
